#!/bin/bash
# EC2 Commands Quick Reference

echo "🚀 EC2 Quick Commands"
echo "===================="
echo ""
echo "IP: 3.104.54.173"
echo ""
echo "Commands yang bisa kamu jalankan:"
echo ""
echo "1. SSH ke EC2:"
echo "   ssh -i \"your-key.pem\" ubuntu@3.104.54.173"
echo ""
echo "2. Pull latest code:"
echo "   cd ~/IP-HCK88-Rahmad"
echo "   git pull origin dev"
echo ""
echo "3. Update .env (jika belum ada):"
echo "   cd ~/IP-HCK88-Rahmad/server"
echo "   nano .env"
echo ""
echo "4. Restart server:"
echo "   pm2 restart booktracker-api"
echo ""
echo "5. Check status:"
echo "   pm2 status"
echo "   pm2 logs booktracker-api"
echo ""
echo "6. Test server:"
echo "   curl http://localhost:4000/"
echo ""
echo "7. Test from outside:"
echo "   curl http://3.104.54.173:4000/"
echo ""
echo "===================="
echo "✅ Security Group port 4000 sudah dibuka!"
echo "📝 Next: SSH ke EC2 dan pull code"
